---
include:
  - project: nci-gdc/gitlab-templates
    ref: master
    file:
      - templates/artifacts/python-library.yaml

tox:
  services:
    - name: rabbitmq
      alias: rabbitmq
  variables:
    RABBITMQ_SERVER: rabbitmq
    RABBITMQ_PORT: 5672
