[metadata]
name = queueclient
description = Queue Client Facade: A generalized API that allows for connection to multiple queue implementations.long_description = file: README.md
long_description = file: README.md
long_description_content_type = text/markdown
author = Gdc feature team
author_email = gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com
maintainer = GDC Feature Team
maintainer_email = gdc_dev_questions-aaaaae2lhsbell56tlvh3upgoq@cdis.slack.com
license = Apache Software License 2.0
license_files = LICENSE
url = https://github.com/NCI-GDC/queueclient
keywords = rabbitmq, depot
classifiers =
    License :: OSI Approved :: Apache Software License
    Topic :: Software Development :: Libraries :: Python Modules
    Topic :: Internet
    Programming Language :: Python
    Programming Language :: Python :: 3.7
    Programming Language :: Python :: 3.8
    Programming Language :: Python :: 3.9
    Programming Language :: Python :: 3.10
    Programming Language :: Python :: 3.11

[options]
zip_safe = True
packages = find:
package_dir =
    =src
python_requires = >=3.7
include_package_data = True
install_requires =
    pika>=1.1
    requests>=2
    simplejson>=3
    deprecated

[options.packages.find]
where = src

[options.extras_require]
dev =
    coverage[toml]
    pytest
    pytest-cov>=2.7.1
    depot==1.0.0
    testcontainers[rabbitmq]>=3.7.1
