[tox]
envlist = py27, py36

[testenv]
commands = pifpaf run rabbitmq -- python -m pytest -vvvs --junit-xml=.report/pytest.xml

deps =
    pytest
    pifpaf
    git+ssh://git@github.com/NCI-GDC/depot.git@ae74895c62987c679a228c801fc2db7993734f3b#egg=depot
