[tox]
envlist = py27, py35

[testenv]
commands = pifpaf run rabbitmq -- python -m pytest -vvvs --junit-xml=.report/pytest.xml

deps =
    pytest
    pifpaf
    git+ssh://git@github.com/NCI-GDC/depot.git@d43bded3b65dafa4d6965262ff51fcaabd64db43#egg=depot