[tox]
envlist = py37

[testenv]
passenv =
    RABBITMQ_*
setenv =
    NO_PROXY=localhost,rabbitmq
    no_proxy=localhost,rabbitmq
extras =
    dev
commands =
    python -m pytest --cov-report html --cov-report xml:coverage.xml --junit-xml report.xml {posargs}


[testenv:publish]
changedir =
passenv =
  TWINE_*
skip_install=true
deps =
    setuptools_scm
    build
    twine
install_command =
    python -m pip install {opts} {packages}
commands =
    python -m setuptools_scm
    python -m build
    python -m twine check dist/*
    python -m twine upload dist/*
commands_post=
